### ISSUE TITLE
Case handling of pasted content

### ISSUE THREAD

**Issue by baechoofarm** [baechoofarm/sketchbox#12]

**Comment by huewilliams** [comment]
Problem : When copy Texts over two lines in view mode and paste it in view mode, space line insert between lines.
![제목 없음](https://user-images.githubusercontent.com/37013834/132612683-685e0661-11d2-4544-a77b-d0fb1ce226e5.png)

**Comment by huewilliams** [comment]
> Problem : When copy Texts over two lines in view mode and paste it in view mode, space line insert between lines.
> ![제목 없음](https://user-images.githubusercontent.com/37013834/132612683-685e0661-11d2-4544-a77b-d0fb1ce226e5.png)

Now We solved this problem by checking empty block and deleting it when insert Text. (8ac734dbe899ab8686b2c4cc96fcadef8046a784)

![제목 없음](https://user-images.githubusercontent.com/37013834/132613861-7a128049-f528-4189-9adc-90b7898b5ae3.png)

**Comment by huewilliams** [comment]
Problem : when copy link(inner paragraph with other texts) in view mode and paste it in edit mode, it didn't wrap link text.
![제목 없음](https://user-images.githubusercontent.com/37013834/132626992-6bd14628-8766-4507-9869-d2764a284f09.png)

**Comment by huewilliams** [comment]
Now We solved right before problem. 
From now on, Sketchbox wrap link whick between texts.
![제목 없음](https://user-images.githubusercontent.com/37013834/132638483-9aa2d9cd-8c82-44c5-b096-28ae3625987d.png)

**Comment by huewilliams** [comment]
Problem : when copy link(that isn't same view text and real url) in view mode and paste it. It didn't wrapped as link.
![제목 없음](https://user-images.githubusercontent.com/37013834/133011656-7dca5cd4-64e6-4b5f-a030-59be6b381729.png)

**Comment by huewilliams** [comment]
Now We solved this problem. Added `deserialize` util function and apply it in `onPaste` handler of Sketchobx.
![제목 없음](https://user-images.githubusercontent.com/37013834/133013697-f43bffe8-345c-4973-9a88-ded1567bd140.png)
