### ISSUE TITLE
Set hyperlink to selected text

### ISSUE THREAD

**Issue by baechoofarm** [baechoofarm/sketchbox#13]

**Comment by huewilliams** [comment]
I implemented this feature in dfb3a395d79fc3f4d3d8d3660d10ced5046b9b00 and 34dd2ca3e3974f49d760dd9733c29fd1606842ab.
I Added `insertLink` function and Added `LinkButton`&`UnLinkButton` to the Demo Editor (https://baechoofarm.github.io/sketchbox/?path=/story/sketchbox-editor--basic).
You can select texts by drag and click `LinkButton` to set Link Element. And Click `UnLinkButton` to reset element.
