### ISSUE TITLE
Editor Toolbar

### ISSUE THREAD

**Issue by baechoofarm** [baechoofarm/sketchbox#19]

**Comment by huewilliams** [comment]
Applied Style to Editor Toolbar.
Apply Google Material Icons and some css for looks good.
And add format buttons. (now we can apply text format with button not only input command!)
`Before Working`
![image](https://user-images.githubusercontent.com/37013834/132614347-c54157c8-91f1-4e98-913b-3114ed87a3d3.png)
`After Working`
![image](https://user-images.githubusercontent.com/37013834/132614414-c2fb5bec-094c-45e2-9cbf-a33482f0de01.png)
